### ISSUE TITLE
python environment

### ISSUE THREAD

**Issue by zachluo** [taeinkwon/h2oplayer#3]
hi Taein,

I found that MANO needs python2 but h2oplayer needs python3. How do handle this?

Best,
Weixin

**Comment by taeinkwon** [comment]
Hi Weixin, 

if you have the Python version problem, it must be the print function problem. You can simply switch print "hello world" to print("hello world").

Best,
Taein Kwon

**Comment by zachluo** [comment]
> Hi Weixin,
> 
> if you have the Python version problem, it must be the print function problem. You can simply switch print "hello world" to print("hello world").
> 
> Best, Taein Kwon

The MANO model is pickle of python2. So it will fail on python3. How do you tackle this problem?
